language: python
python:
  - "2.7"
install: 
  - "pip install -r requirements-test.txt --use-mirrors"
  - "pip install coveralls"
  - "python setup.py install"
script: 
  nosetests --with-coverage --cover-inclusive
after_success:
  coveralls
